# Generated by Django 5.2.7 on 2025-10-20 13:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="JobTitle",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name="Candidate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("years_of_experience", models.IntegerField()),
                ("skills", models.TextField()),
                ("education", models.TextField()),
                ("past_experience", models.TextField()),
                (
                    "job_title",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="cvs.jobtitle"
                    ),
                ),
            ],
        ),
    ]
