# Generated by Django 5.2.7 on 2025-10-20 13:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("cvs", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Candidate",
            new_name="CV",
        ),
    ]
